api_platform:
    title: 'Vehicles API'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    defaults:
        path_prefix: '/api/v1'
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
